{% set name = "scikit-explain" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c89edf0e4994652a5b98a68b6cdeb3da5ecf27bcbac0b54c2928c380938a719

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}

  run:
    - ipywidgets
    - lime >=0.2.0
    - matplotlib-base
    - numpy
    - pandas
    - python >={{ python_min }}
    - scikit-learn >=1.0.0
    - seaborn >=0.11.0
    - shap >=0.30.0
    - statsmodels
    - tqdm
    - xarray >=0.16.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

  imports:
    - skexplain
    - skexplain.common
    - skexplain.main
    - skexplain.main.PermutationImportance
    - skexplain.plot

about:
  home: https://github.com/monte-flora/scikit-explain/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A user-friendly python package for computing and plotting machine learning explainability output.
  doc_url: https://scikit-explain.readthedocs.io
  dev_url: https://github.com/monte-flora/scikit-explain/

extra:
  recipe-maintainers:
    - monte-flora
